networks:
  passenger_app_net:
    driver: bridge
services:
  passenger_backend:
    env_file:
      - .env
    container_name: passenger_backend
    build:
      context: passenger-transportation-service
    networks:
      - passenger_app_net
    ports:
      - "8080:8080"
  passenger_frontend:
    container_name: passenger_frontend
    build:
      context: passenger-transportation-frontend
    networks:
      - passenger_app_net
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 1m
    ports:
      - "80:80"
