networks:
  passenger_app_net:
    driver: bridge
services:
  passenger_backend:
    env_file:
      - .env
    container_name: passenger_backend
    build:
      context: passenger-transportation-service
    networks:
      - passenger_app_net
    environment:
      - spring.profiles.active=prod
    healthcheck:
      test: curl --fail http://localhost:${PORT}/actuator/health || exit 1
      interval: 1m
      timeout: 30s
      retries: 2
      start_period: 1m
    ports:
      - ${PORT}:${PORT}
  passenger_frontend:
    container_name: passenger_frontend
    build:
      context: passenger-transportation-frontend
    networks:
      - passenger_app_net
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      timeout: 30s
      retries: 2
      start_period: 1m
    ports:
      - "80:80"
