CREATE TABLE IF NOT EXISTS t_user
(
    id    bigint generated by default as identity primary key ,
    phone VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE
);

CREATE TABLE user_data
(
    id        bigint primary key references t_user (id) ON DELETE CASCADE,
    name      varchar(128) NOT NULL,
    last_name varchar(128) NOT NULL,
    age       smallint     NOT NULL check (age > 0 and age < 100),
    sex       bool         NOT NULL,
    user_type varchar(128) NOT NULL default 'DEFAULT'
);

CREATE TABLE credential_data
(
    id bigint primary key references t_user (id) ON DELETE CASCADE,
    card varchar(255) NOT NULL,
    cvc bit NOT NULL,
    expired_date TIMESTAMP NOT NULL check ( CURRENT_TIMESTAMP < expired_date)
)