spring:
  application:
    name: passanger-transportation-graph-jpa-adapter
  datasource:
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: passwd
    url: jdbc:sqlite:transportation.db
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
