spring:
  cache:
    type: redis
  datasource:
    driver-class-name: ${SQL_DRIVER}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      repositories:
        enabled: false
      port: ${REDIS_PORT}
  mvc:
    servlet:
      path: ${SERVLET_PATH:/api/v1/booking}
  jpa:
    database-platform: ${SQL_DIALECT}
    show-sql: ${SHOW_SQL:true}
  threads:
    virtual:
      enabled: true

server:
  port: ${PORT:8080}
springdoc:
  api-docs:
    path: ${SWAGGER_API_PATH:/docs/}
  swagger-ui:
    path: ${SWAGGER_PATH:/swagger/}
  override-with-generic-response: false
logging:
  level:
    org.service: ${LOG_LEVEL:error}
  file:
    name: ${LOG_FILE_NAME:app.log}
  logback:
    rollingpolicy:
      max-file-size: ${LOG_MAX_FILE_SIZE:20MB}
  threshold:
    file: ${LOG_LEVEL_FILE:ERROR}
