spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: passwd
    url: jdbc:sqlite:transportation.db
  sql:
    init:
      mode: always
  mvc:
    servlet:
      path: /api/v1/booking
server:
  port: 8080
cache:
  lru:
    size: 20