spring:
  cache:
    type: simple
  datasource:
    driver-class-name: ${SQL_DRIVER}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    url: ${SQL_URL}

  mvc:
    servlet:
      path: ${SERVLET_PATH:/api/v1/booking}
  flyway:
    driver-class-name:  ${SQL_DRIVER}
    url: ${SQL_URL}
    user: ${SQL_USERNAME}
    password:  ${SQL_PASSWORD}

  jpa:
    database-platform: ${SQL_DIALECT}
    show-sql: ${SHOW_SQL:true}
  properties:
    hibernate:
      order_inserts: true
      jdbc.batch_size: 7
  threads:
    virtual:
      enabled: true
server:
  port: ${PORT:8080}
cache:
  lru:
    size: ${LRU_CACHE_SIZE:100}
springdoc:
  api-docs:
    path: ${SWAGGER_API_PATH:/docs/}
  swagger-ui:
    path: ${SWAGGER_PATH:/swagger/}
  override-with-generic-response: false
logging:

  level:
    org.service: ${LOG_LEVEL:error}
  file:
    name: ${LOG_FILE_NAME:app.log}
  logback:
    rollingpolicy:
      max-file-size: ${LOG_MAX_FILE_SIZE:20MB}
  threshold:
    file: ${LOG_LEVEL_FILE:ERROR}