spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: passwd
    url: jdbc:sqlite:transportation.db
  mvc:
    servlet:
      path: /api/v1/booking
  flyway:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:transportation.db
    user: admin
    password: passwd
server:
  port: 8080
cache:
  lru:
    size: 20
