spring:
  cache:
    type: simple
  datasource:
    driver-class-name: ${SQLITE_DRIVER}
    username: ${SQLITE_USERNAME}
    password: ${SQLITE_PASSWORD}
    url: ${SQLITE_URL}
  mvc:
    servlet:
      path: ${SERVLET_PATH:/api/v1/booking}
  flyway:
    driver-class-name:  ${SQLITE_DRIVER}
    url: ${SQLITE_URL}
    user: ${SQLITE_USERNAME}
    password:  ${SQLITE_PASSWORD}
  jpa:
    database-platform: ${SQLITE_DIALECT}
    show-sql: true
  threads:
    virtual:
      enabled: true
  config:
    import: optional:file:.env[.properties]
server:
  port: 8080
cache:
  lru:
    size: 20
springdoc:
  api-docs:
    path: ${SWAGGER_API_PATH:/docs/}
  swagger-ui:
    path: ${SWAGGER_PATH:/swagger/}
  override-with-generic-response: false
logging:
  level:
    org.service: error
  file:
    name: ${LOG_FILE_NAME:app.log}
  logback:
    rollingpolicy:
      max-file-size: ${LOG_MAX_FILE_SIZE:20MB}
  threshold:
    file: ERROR
