name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and Test Backend
        run: |
          cd passenger-transportation-service
          mvn clean test package

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies and Build Frontend
        run: |
          cd passenger-transportation-frontend
          npm install
          npm run build

  docker-build-and-deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    env:
      DEPLOY_ENV: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Images
        run: docker-compose build

      - name: Deploy with Docker Compose
        run: docker-compose up -d

      - name: Post-Deployment Health Check
        run: |
          curl --fail http://localhost:${{ secrets.PORT || '8080' }} || exit 1
